#!/bin/sh

# Stash all changes that have not been staged for commit.
# This means that we will only run the tests against
# the state the code would be in if this commit was
# allowed.
old_stash=$(git rev-parse -q --verify refs/stash)
git stash save -q -u --keep-index
new_stash=$(git rev-parse -q --verify refs/stash)

# Run tests
HOME=$(git rev-parse --show-toplevel)
cd $HOME
pip install -e .
pytest
status=$?

# Restore changes only if we actually stashed changes.
if [ "$old_stash" != "$new_stash" ]; then
	git reset --hard -q && git stash apply --index -q && git stash drop -q
fi

# Exit with status from test-run: nonzero prevents commit
if [ $status -ne 0 ]; then
    echo -e "\e[31mCode NOT committed because the tests failed. If you need to bypass this, add --no-verify to the commit command.\e[0m"
fi
exit $status
